services:

    JTG\Mark\Markdown\EnvironmentProvider:
        class: JTG\Mark\Markdown\EnvironmentProvider

    JTG\Mark\Markdown\MarkdownConverter:
        class: JTG\Mark\Markdown\MarkdownConverter
        arguments:
            $provider: '@JTG\Mark\Markdown\EnvironmentProvider'

    JTG\Mark\Render\HtmlRenderer:
        class: JTG\Mark\Render\HtmlRenderer
        arguments:
            $twigEnv: '@JTG\Mark\Twig\TwigEnv'
            $outputDir: '%mark.project.root_dir%/build'

    JTG\Mark\Repository\PostRepository:
        class: JTG\Mark\Repository\PostRepository
        arguments:
            $directory: '%mark.project.root_dir%/dist/posts'

    JTG\Mark\Service\MarkManager:
        class: JTG\Mark\Service\MarkManager
        arguments:
            $postRepository: '@JTG\Mark\Repository\PostRepository'
            $markdownConverter: '@JTG\Mark\Markdown\MarkdownConverter'
            $htmlRenderer: '@JTG\Mark\Render\HtmlRenderer'

    JTG\Mark\Twig\TwigEnv:
        class: JTG\Mark\Twig\TwigEnv
        arguments:
            $templateDirs:
                - '%mark.kernel.root_dir%/dist/templates'
                - '%mark.project.root_dir%/dist/templates'
