parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    JTG\Mark\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Dto/'
            - '../src/Event/'
            - '../src/Kernel/'
            - '../src/Repository/'
            - '../src/Util/'

    JTG\Mark\MarkApplication:
        public: true
        arguments:
            - !tagged command

    Symfony\Component\DependencyInjection\ParameterBag\ContainerBag:
        public: true
        arguments:
            $container: '@service_container'

    Symfony\Component\EventDispatcher\EventDispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        public: true

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: [ 'command' ]

        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags: [ 'mark.event_subscriber' ]
