parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $kernelTemplateDir: '%kernel.root_dir%/dist/templates'
            $projectTemplateDir: '%project.root_dir%/dist/templates'
            $projectPostDir: '%project.root_dir%/dist/posts'
            $projectOutputDir: '%project.root_dir%/build'

    JTG\Mark\:
        resource: '../src/'
        exclude:
            - '../src/Kernel/'
            - '../src/Model/'

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: [ 'command' ]

    JTG\Mark\MarkApplication:
        public: true
        arguments:
            - !tagged command

    Symfony\Component\DependencyInjection\ParameterBag\ContainerBag:
        public: true
        arguments:
            $container: '@service_container'

    Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface: '@Symfony\Component\DependencyInjection\ParameterBag\ContainerBag'
